### ISSUE TITLE
iron-icons not showing after one reload

### ISSUE THREAD

**Issue by yorrd** [meteorwebcomponents/synthesis-demo#2]
I'm hosting this on my git server, whenever I push once (and the server reloads), the iron-icons are gone. Everything else seems to be fine. Can you reproduce this?

**Comment by aruntk** [comment]
@yorrd checking. In the meantime check if this https://github.com/aruntk/kickstart-meteor-polymer is working. I've not updated synthesis-demo project in a while. Maybe thats the reason.

**Comment by aruntk** [comment]
@yorrd check now.

**Comment by yorrd** [comment]
@aruntk sorry for the late reply.

You have so many demo projects ^.^ which one is made for what purpose?

I'm currently using this one again, however it gives me an error whenever I try to start it.

`
   imports/ui/imports.html:4: Expected one of: <body>, <head>, <template>
   imports/ui/layouts/test-layout.html:1: Expected one of: <body>, <head>, <template>
   imports/ui/components/test-element.html:1: Expected one of: <body>, <head>, <template>
`

Do you have any idea what I may have missed?

**Comment by aruntk** [comment]
Actively maintained demos.

https://github.com/meteorwebcomponents/synthesis-demo - This repo is a basic demo (port of meteor counter demo).

https://github.com/aruntk/kickstart-meteor-polymer-with-app-route - complete meteor polymer boilerplate. This is recommended as a starting point for your app. 

https://github.com/aruntk/kickstart-meteor-polymer - Same with flow-router instead of app-route

https://github.com/aruntk/kickstart-meteor-polymer-with-auth - Kickstarter app with sign in and sign up + logout button. Authentication demo. Flow router for routing.

Regarding the error I'm not able to recreate it. Try running meteor update. If that doesn't work try cloning the repo and starting from scratch.

**Comment by yorrd** [comment]
You're awesome man. Thanks for the great work, I've been using Synthesis and those bootstrap projects for quite some time now.

The issue was fixed by removing the blaze compiler, didn't realize I had to take care of that

**Comment by aruntk** [comment]
@yorrd Welcome mate . :)
